name: Archive
on:
#  push:
#    branches: [ "main" ]
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      - name: Run a one-line script
        run: ./download.sh
