name: Archive
on:
    push:
      branches: [ "main" ]

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      - uses: AnimMouse/setup-yt-dlp@v1
      - name: Download
        run: |
          ./download.sh
