name: Archive
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ "main" ]

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: AnimMouse/setup-yt-dlp@v1
        with:
          with-ffmpeg: true
      - name: Download
        run: |
          ./scripts/download.sh
      - uses: EndBug/add-and-commit@v9
