name: Archive
on:
  schedule:
    - cron: '0 16 * * *'
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{github.repository}}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  archive:
    runs-on:
      - ubuntu-latest
      # - self-hosted
    permissions:
      contents: write
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: aria2 uuid-runtime python3 python3-mutagen python3-certifi ca-certificates python3-brotli python3-websockets python3-xattr python3-pycryptodome python3-m3u8 httpie ffmpeg
      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v1
      - uses: actions/checkout@v4
      - name: Download
        run: ./scripts/download.sh
      - uses: EndBug/add-and-commit@v9
      - uses: gautamkrishnar/keepalive-workflow@v1
